-- _anim_maps_generated.lua - SCRATCH OUTPUT, for review only.
-- Generated by tools/gen_anim_maps.py from npc_heroes.json + npc_abilities.json.
-- This is the full register_anim_maps() body for the modern hero pool.
-- Do NOT require() this file; the main thread reviews it and integrates the
-- blocks into Sniper.lua's register_anim_maps() by hand. Re-run the generator
-- after a patch instead of hand-editing.


    -- bane
    Anim.RegisterMap("npc_dota_hero_bane", {
        [AB3] = { ability = "bane_nightmare", role = "hard_disable" },
        [AB4] = { ability = "bane_fiends_grip", role = "channel_start" },
    })
    -- batrider
    Anim.RegisterMap("npc_dota_hero_batrider", {
        [AB4] = { ability = "batrider_flaming_lasso", role = "hard_disable" },
    })
    -- beastmaster
    Anim.RegisterMap("npc_dota_hero_beastmaster", {
        [AB4] = { ability = "beastmaster_primal_roar", role = "hard_disable" },
    })
    -- bloodseeker
    Anim.RegisterMap("npc_dota_hero_bloodseeker", {
        [AB4] = { ability = "bloodseeker_rupture", role = "ult_burst" },
    })
    -- chaos_knight
    Anim.RegisterMap("npc_dota_hero_chaos_knight", {
        [AB1] = { ability = "chaos_knight_chaos_bolt", role = "hard_disable" },
        [AB2] = { ability = "chaos_knight_reality_rift", role = "gap_close" },
    })
    -- clinkz
    Anim.RegisterMap("npc_dota_hero_clinkz", {
        [AB5] = { ability = "clinkz_burning_barrage", role = "channel_start" },  -- (draft)
    })
    -- crystal_maiden
    Anim.RegisterMap("npc_dota_hero_crystal_maiden", {
        [AB4] = { ability = "crystal_maiden_freezing_field", role = "channel_start" },
    })
    -- dark_willow
    Anim.RegisterMap("npc_dota_hero_dark_willow", {
        [AB1] = { ability = "dark_willow_bramble_maze", role = "hard_disable" },
        [AB3] = { ability = "dark_willow_cursed_crown", role = "hard_disable" },
        [AB4] = { ability = "dark_willow_terrorize", role = "hard_disable" },
    })
    -- dawnbreaker
    Anim.RegisterMap("npc_dota_hero_dawnbreaker", {
        [AB2] = { ability = "dawnbreaker_celestial_hammer", role = "gap_close" },
        [AB4] = { ability = "dawnbreaker_solar_guardian", role = "channel_start" },  -- (draft)
    })
    -- disruptor
    Anim.RegisterMap("npc_dota_hero_disruptor", {
        [AB4] = { ability = "disruptor_static_storm", role = "hard_disable" },
    })
    -- drow_ranger
    Anim.RegisterMap("npc_dota_hero_drow_ranger", {
        [AB3] = { ability = "drow_ranger_multishot", role = "channel_start" },  -- (draft)
    })
    -- earth_spirit
    Anim.RegisterMap("npc_dota_hero_earth_spirit", {
        [AB2] = { ability = "earth_spirit_rolling_boulder", role = "hard_disable" },
    })
    -- earthshaker
    Anim.RegisterMap("npc_dota_hero_earthshaker", {
        [AB4] = { ability = "earthshaker_echo_slam", role = "hard_disable" },
    })
    -- elder_titan
    Anim.RegisterMap("npc_dota_hero_elder_titan", {
        [AB1] = { ability = "elder_titan_echo_stomp", role = "channel_start" },  -- (draft)
    })
    -- enigma
    Anim.RegisterMap("npc_dota_hero_enigma", {
        [AB1] = { ability = "enigma_malefice", role = "hard_disable" },
        [AB4] = { ability = "enigma_black_hole", role = "hard_disable" },
    })
    -- faceless_void
    Anim.RegisterMap("npc_dota_hero_faceless_void", {
        [AB4] = { ability = "faceless_void_chronosphere", role = "hard_disable" },
    })
    -- grimstroke
    Anim.RegisterMap("npc_dota_hero_grimstroke", {
        [AB2] = { ability = "grimstroke_ink_creature", role = "hard_disable" },
        [AB4] = { ability = "grimstroke_soul_chain", role = "channel_start" },
    })
    -- hoodwink
    Anim.RegisterMap("npc_dota_hero_hoodwink", {
        [AB2] = { ability = "hoodwink_bushwhack", role = "hard_disable" },
    })
    -- huskar
    Anim.RegisterMap("npc_dota_hero_huskar", {
        [AB4] = { ability = "huskar_life_break", role = "gap_close" },
    })
    -- jakiro
    Anim.RegisterMap("npc_dota_hero_jakiro", {
        [AB2] = { ability = "jakiro_ice_path", role = "hard_disable" },
    })
    -- keeper_of_the_light
    Anim.RegisterMap("npc_dota_hero_keeper_of_the_light", {
        [AB1] = { ability = "keeper_of_the_light_illuminate", role = "channel_start" },  -- (draft)
    })
    -- kez
    Anim.RegisterMap("npc_dota_hero_kez", {
        [AB2] = { ability = "kez_grappling_claw", role = "gap_close" },
        [AB4] = { ability = "kez_raptor_dance", role = "hard_disable" },
    })
    -- leshrac
    Anim.RegisterMap("npc_dota_hero_leshrac", {
        [AB1] = { ability = "leshrac_split_earth", role = "hard_disable" },
    })
    -- lich
    Anim.RegisterMap("npc_dota_hero_lich", {
        [AB3] = { ability = "lich_sinister_gaze", role = "channel_start" },
        [AB4] = { ability = "lich_chain_frost", role = "ult_burst" },
    })
    -- life_stealer
    Anim.RegisterMap("npc_dota_hero_life_stealer", {
        [AB2] = { ability = "life_stealer_open_wounds", role = "hard_disable" },
    })
    -- lina
    Anim.RegisterMap("npc_dota_hero_lina", {
        [AB2] = { ability = "lina_light_strike_array", role = "hard_disable" },
        [AB4] = { ability = "lina_laguna_blade", role = "ult_burst" },
    })
    -- lion
    Anim.RegisterMap("npc_dota_hero_lion", {
        [AB1] = { ability = "lion_impale", role = "hard_disable" },
        [AB2] = { ability = "lion_voodoo", role = "hard_disable" },
        [AB3] = { ability = "lion_mana_drain", role = "hard_disable" },
        [AB4] = { ability = "lion_finger_of_death", role = "ult_burst" },
    })
    -- magnataur
    Anim.RegisterMap("npc_dota_hero_magnataur", {
        [AB3] = { ability = "magnataur_skewer", role = "hard_disable" },
        [AB4] = { ability = "magnataur_reverse_polarity", role = "hard_disable" },
    })
    -- marci
    Anim.RegisterMap("npc_dota_hero_marci", {
        [AB1] = { ability = "marci_grapple", role = "gap_close" },
    })
    -- mars
    Anim.RegisterMap("npc_dota_hero_mars", {
        [AB1] = { ability = "mars_spear", role = "hard_disable" },
        [AB2] = { ability = "mars_gods_rebuke", role = "hard_disable" },
        [AB4] = { ability = "mars_arena_of_blood", role = "hard_disable" },
    })
    -- mirana
    Anim.RegisterMap("npc_dota_hero_mirana", {
        [AB2] = { ability = "mirana_arrow", role = "hard_disable" },
    })
    -- morphling
    Anim.RegisterMap("npc_dota_hero_morphling", {
        [AB2] = { ability = "morphling_adaptive_strike_agi", role = "hard_disable" },
    })
    -- muerta
    Anim.RegisterMap("npc_dota_hero_muerta", {
        [AB1] = { ability = "muerta_dead_shot", role = "hard_disable" },
    })
    -- naga_siren
    Anim.RegisterMap("npc_dota_hero_naga_siren", {
        [AB2] = { ability = "naga_siren_ensnare", role = "hard_disable" },
        [AB4] = { ability = "naga_siren_song_of_the_siren", role = "hard_disable" },
    })
    -- necrolyte
    Anim.RegisterMap("npc_dota_hero_necrolyte", {
        [AB4] = { ability = "necrolyte_reapers_scythe", role = "ult_burst" },
    })
    -- nyx_assassin
    Anim.RegisterMap("npc_dota_hero_nyx_assassin", {
        [AB1] = { ability = "nyx_assassin_impale", role = "hard_disable" },
        [AB4] = { ability = "nyx_assassin_vendetta", role = "gap_close" },
    })
    -- obsidian_destroyer
    Anim.RegisterMap("npc_dota_hero_obsidian_destroyer", {
        [AB2] = { ability = "obsidian_destroyer_astral_imprisonment", role = "hard_disable" },
        [AB4] = { ability = "obsidian_destroyer_sanity_eclipse", role = "ult_burst" },
    })
    -- oracle
    Anim.RegisterMap("npc_dota_hero_oracle", {
        [AB1] = { ability = "oracle_fortunes_end", role = "channel_start" },
    })
    -- pangolier
    Anim.RegisterMap("npc_dota_hero_pangolier", {
        [AB1] = { ability = "pangolier_swashbuckle", role = "gap_close" },
        [AB4] = { ability = "pangolier_gyroshell", role = "gap_close" },
    })
    -- phantom_assassin
    Anim.RegisterMap("npc_dota_hero_phantom_assassin", {
        [AB2] = { ability = "phantom_assassin_phantom_strike", role = "gap_close" },
    })
    -- primal_beast
    Anim.RegisterMap("npc_dota_hero_primal_beast", {
        [AB1] = { ability = "primal_beast_onslaught", role = "gap_close" },
        [AB4] = { ability = "primal_beast_pulverize", role = "channel_start" },
    })
    -- puck
    Anim.RegisterMap("npc_dota_hero_puck", {
        [AB2] = { ability = "puck_waning_rift", role = "hard_disable" },
        [AB3] = { ability = "puck_phase_shift", role = "channel_start" },  -- (draft)
        [AB4] = { ability = "puck_dream_coil", role = "hard_disable" },
    })
    -- pudge
    Anim.RegisterMap("npc_dota_hero_pudge", {
        [AB1] = { ability = "pudge_meat_hook", role = "gap_close" },
        [AB4] = { ability = "pudge_dismember", role = "channel_start" },
    })
    -- pugna
    Anim.RegisterMap("npc_dota_hero_pugna", {
        [AB4] = { ability = "pugna_life_drain", role = "hard_disable" },
    })
    -- rattletrap
    Anim.RegisterMap("npc_dota_hero_rattletrap", {
        [AB4] = { ability = "rattletrap_hookshot", role = "gap_close" },
    })
    -- riki
    Anim.RegisterMap("npc_dota_hero_riki", {
        [AB3] = { ability = "riki_tricks_of_the_trade", role = "channel_start" },  -- (draft)
    })
    -- ringmaster
    Anim.RegisterMap("npc_dota_hero_ringmaster", {
        [AB1] = { ability = "ringmaster_tame_the_beasts", role = "channel_start" },  -- (draft)
        [AB3] = { ability = "ringmaster_impalement", role = "hard_disable" },
        [AB4] = { ability = "ringmaster_wheel", role = "hard_disable" },
    })
    -- sand_king
    Anim.RegisterMap("npc_dota_hero_sand_king", {
        [AB1] = { ability = "sandking_burrowstrike", role = "hard_disable" },
        [AB4] = { ability = "sandking_epicenter", role = "hard_disable" },
    })
    -- shadow_demon
    Anim.RegisterMap("npc_dota_hero_shadow_demon", {
        [AB1] = { ability = "shadow_demon_disruption", role = "hard_disable" },
        [AB4] = { ability = "shadow_demon_demonic_purge", role = "hard_disable" },
    })
    -- shadow_shaman
    Anim.RegisterMap("npc_dota_hero_shadow_shaman", {
        [AB2] = { ability = "shadow_shaman_voodoo", role = "hard_disable" },
        [AB3] = { ability = "shadow_shaman_shackles", role = "channel_start" },
    })
    -- skywrath_mage
    Anim.RegisterMap("npc_dota_hero_skywrath_mage", {
        [AB3] = { ability = "skywrath_mage_ancient_seal", role = "hard_disable" },
        [AB4] = { ability = "skywrath_mage_mystic_flare", role = "hard_disable" },
    })
    -- slark
    Anim.RegisterMap("npc_dota_hero_slark", {
        [AB2] = { ability = "slark_pounce", role = "gap_close" },
    })
    -- snapfire
    Anim.RegisterMap("npc_dota_hero_snapfire", {
        [AB1] = { ability = "snapfire_scatterblast", role = "ult_burst" },
        [AB4] = { ability = "snapfire_mortimer_kisses", role = "hard_disable" },
    })
    -- spirit_breaker
    Anim.RegisterMap("npc_dota_hero_spirit_breaker", {
        [AB1] = { ability = "spirit_breaker_charge_of_darkness", role = "gap_close" },
        [AB4] = { ability = "spirit_breaker_nether_strike", role = "hard_disable" },
    })
    -- storm_spirit
    Anim.RegisterMap("npc_dota_hero_storm_spirit", {
        [AB2] = { ability = "storm_spirit_electric_vortex", role = "hard_disable" },
        [AB4] = { ability = "storm_spirit_ball_lightning", role = "gap_close" },
    })
    -- sven
    Anim.RegisterMap("npc_dota_hero_sven", {
        [AB1] = { ability = "sven_storm_bolt", role = "hard_disable" },
    })
    -- tidehunter
    Anim.RegisterMap("npc_dota_hero_tidehunter", {
        [AB4] = { ability = "tidehunter_ravage", role = "hard_disable" },
    })
    -- tinker
    Anim.RegisterMap("npc_dota_hero_tinker", {
        [AB4] = { ability = "tinker_rearm", role = "channel_start" },  -- (draft)
    })
    -- tiny
    Anim.RegisterMap("npc_dota_hero_tiny", {
        [AB2] = { ability = "tiny_toss", role = "hard_disable" },
    })
    -- treant
    Anim.RegisterMap("npc_dota_hero_treant", {
        [AB4] = { ability = "treant_overgrowth", role = "hard_disable" },
    })
    -- tusk
    Anim.RegisterMap("npc_dota_hero_tusk", {
        [AB1] = { ability = "tusk_ice_shards", role = "hard_disable" },
        [AB2] = { ability = "tusk_snowball", role = "gap_close" },
    })
    -- vengefulspirit
    Anim.RegisterMap("npc_dota_hero_vengefulspirit", {
        [AB4] = { ability = "vengefulspirit_nether_swap", role = "hard_disable" },
    })
    -- void_spirit
    Anim.RegisterMap("npc_dota_hero_void_spirit", {
        [AB1] = { ability = "void_spirit_aether_remnant", role = "hard_disable" },
        [AB4] = { ability = "void_spirit_astral_step", role = "gap_close" },
    })
    -- warlock
    Anim.RegisterMap("npc_dota_hero_warlock", {
        [AB3] = { ability = "warlock_upheaval", role = "channel_start" },  -- (draft)
    })
    -- windrunner
    Anim.RegisterMap("npc_dota_hero_windrunner", {
        [AB1] = { ability = "windrunner_shackleshot", role = "hard_disable" },
        [AB2] = { ability = "windrunner_powershot", role = "channel_start" },  -- (draft)
    })
    -- winter_wyvern
    Anim.RegisterMap("npc_dota_hero_winter_wyvern", {
        [AB4] = { ability = "winter_wyvern_winters_curse", role = "hard_disable" },
    })
    -- witch_doctor
    Anim.RegisterMap("npc_dota_hero_witch_doctor", {
        [AB4] = { ability = "witch_doctor_death_ward", role = "channel_start" },
    })
    -- zuus
    Anim.RegisterMap("npc_dota_hero_zuus", {
        [AB2] = { ability = "zuus_lightning_bolt", role = "ult_burst" },
        [AB4] = { ability = "zuus_thundergods_wrath", role = "ult_burst" },
    })
